### ISSUE TITLE
[swm-gaps] gaps should not be applied to transient windows

### ISSUE THREAD

**Issue by lepisma** [stumpwm/stumpwm-contrib#75]
_From @jakecoble on July 14, 2017 14:44_

Transient windows should not have gaps applied to them. This often causes them to shrink unusably small.

_Copied from original issue: lepisma/swm-gaps#3_

**Comment by lepisma** [comment]
Did you mean the transient windows like 
![image](https://user-images.githubusercontent.com/2487306/28233213-39eeb972-68c3-11e7-8dad-9fe87be12832.png) these ones (I can see the problem here with >0 inner gap) or windows from _floating group_? I believe floating group doesn't get any extra padding.

**Comment by lepisma** [comment]
_From @jakecoble on July 14, 2017 22:47_

Ah, that explains why I wasn't able to fix the problem – I thought transient windows were a part of the floating group.

**Comment by lepisma** [comment]
3a79995 skips adding inner gaps to transients. When transient window gravity is set to `top`, something like the following happens.

 ![image](https://user-images.githubusercontent.com/2487306/28235950-4c6fde7c-68e7-11e7-88d5-f614af1bf6e9.png)

The correct way to fix this would be to check for transient window gravity and move the `y` value down if its `:top` (similarly for other alignments) to align things neatly. Will fix this soon.

**Comment by dbjergaard** [comment]
Is this fixed now?

**Comment by lepisma** [comment]
The main issue (gaps on transients) is fixed. The adjustment for non center gravity is not because I don't think just adjusting x or y value will do. For example the transient below needs to get its width adjusted too (the main window is firefox in background):

![image](https://user-images.githubusercontent.com/2487306/39504304-2d9bb7e2-4dba-11e8-9a1a-ef12b95756ad.png)

They probably need a more extensive handling using the current window width (height) or something. Maybe close this _specific_ issue since its premise is covered.

**Comment by podiki** [comment]
I still have the issue with shrinking transient windows on the latest version. I think related is making some windows floating (e.g. Steam windows) will have them move (slowly or quickly) in some direction until completely off screen.

**Comment by jakecoble** [comment]
> I still have the issue with shrinking transient windows on the latest version. I think related is making some windows floating (e.g. Steam windows) will have them move (slowly or quickly) in some direction until completely off screen.

I still have this issue as well, but I don't think my initial bug report was well stated – we may be using _transient_ colloquially when it has a specific usage in this case. While the Steam windows in question don't stick around long, I don't know if they're transient in any meaningful way. I've yet to figure out what is unique about the windows I'm having trouble with.

**Comment by jakecoble** [comment]
Appears to be windows with a maximum size set that are having trouble. Suggest closing the issue and I'll open another with the new problem description.

**Comment by podiki** [comment]
@jakecoble did you find a better way to describe this? Probably we need to find out what properties are different for these types of windows. I noticed it is often for a loading/splash window, like starting Steam, Zoom, I think for some Wine windows too.

**Comment by jakecoble** [comment]
@podiki Never did track it down. I'll need to find some way to generate a bunch of windows with different properties for testing this, but I haven't yet found a convenient tool for that.

**Comment by podiki** [comment]
@jakecoble This may be solved with fixing #178, basically not applying gaps to windows that are too small to need them. Fixes this for for me for Steam loading/login, Zoom loading at least.
